# 工作流名称
name: Upload IPA to App Store

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '要上传的 Release 标签 (例如: my-app-v1.2)'
        required: true
        type: string

jobs:
  upload:
    runs-on: macos-latest
    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 GitHub CLI 工具
      - name: Install GitHub CLI
        run: brew install gh

      # 从 GitHub Release 下载 .ipa 文件
      - name: Download IPA from Release
        run: gh release download ${{ github.event.inputs.release_tag }} --pattern '*.ipa'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # 设置 Ruby 环境
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # 安装 Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # 创建 API Key 临时文件
      - name: Create API Key file
        run: |
          mkdir -p $HOME/private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > $HOME/private_keys/AuthKey.p8

      # 核心步骤：使用环境变量 + Fastlane 上传
      - name: Upload to App Store Connect with Fastlane
        # ⭐️ 关键改动：在这里定义环境变量
        env:
          # Fastlane 会自动读取这些特定名称的环境变量
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_FILEPATH: "$HOME/private_keys/AuthKey.p8"
        run: |
          # 寻找 .ipa 文件路径
          IPA_PATH=$(find . -name "*.ipa" | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "错误：在 Release 中没有找到 .ipa 文件。"
            exit 1
          fi

          # ⭐️ 命令变得极其简单，Fastlane 会自动从环境中寻找认证信息
          fastlane run upload_to_app_store ipa: "$IPA_PATH"
