# 工作流名称
name: Upload IPA to App Store

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '要上传的 Release 标签 (例如: my-app-v1.2)'
        required: true
        type: string

jobs:
  upload:
    runs-on: macos-latest
    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 GitHub CLI 工具
      - name: Install GitHub CLI
        run: brew install gh

      # 从 GitHub Release 下载 .ipa 文件
      - name: Download IPA from Release
        run: gh release download ${{ github.event.inputs.release_tag }} --pattern '*.ipa'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # 设置 Ruby 环境
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # 安装 Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # ⭐️ 新增步骤：将 API Key 内容写入临时文件
      - name: Create API Key file
        run: |
          mkdir -p $HOME/private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > $HOME/private_keys/AuthKey.p8

      # 核心步骤：使用 Fastlane 和 API Key 文件路径进行上传
      - name: Upload to App Store Connect with Fastlane
        run: |
          # 寻找 .ipa 文件路径
          IPA_PATH=$(find . -name "*.ipa" | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "错误：在 Release 中没有找到 .ipa 文件。"
            exit 1
          fi

          # 调用 fastlane，这次使用 api_key_path 指向我们创建的密钥文件
          fastlane run upload_to_app_store \
            api_key_path: "$HOME/private_keys/AuthKey.p8" \
            api_issuer: '${{ secrets.ISSUER_ID }}' \
            ipa: "$IPA_PATH"
