# 工作流名称
name: Upload IPA to App Store

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '要上传的 Release 标签 (包名)'
        required: true
        type: string

jobs:
  upload:
    runs-on: macos-latest
    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 GitHub CLI 工具
      - name: Install GitHub CLI
        run: brew install gh

      # ⭐️ 新增的终极诊断步骤：在下载前，先列出该 Release 的附件信息
      - name: "Debug: List assets for the tag"
        run: |
          echo "Checking assets for tag: ${{ github.event.inputs.release_tag }}"
          gh release view ${{ github.event.inputs.release_tag }} --json assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 从 GitHub Release 下载 .ipa 文件
      - name: Download IPA from Release
        run: gh release download ${{ github.event.inputs.release_tag }} --pattern '*.ipa'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # 验证文件是否存在
      - name: Verify downloaded files
        run: |
          echo "Verifying contents of the current directory..."
          ls -R

      # ... 后续步骤保持不变 ...
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Fastlane
        run: gem install fastlane
      - name: Create API Key file
        run: |
          mkdir -p $HOME/private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > $HOME/private_keys/AuthKey.p8
      - name: Upload to App Store Connect with Fastlane
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_FILEPATH: "$HOME/private_keys/AuthKey.p8"
        run: |
          IPA_PATH=$(find . -name "*.ipa" | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "错误：脚本在当前目录中没有找到 .ipa 文件。请检查上一步 'Verify downloaded files' 的输出。"
            exit 1
          fi
          fastlane run upload_to_app_store ipa: "$IPA_PATH"
