# 工作流名称
name: Upload IPA to App Store (via Fastlane)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '要上传的 Release 标签 (例如: my-app-v1.2)'
        required: true
        type: string

jobs:
  upload:
    runs-on: macos-latest
    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 GitHub CLI 工具
      - name: Install GitHub CLI
        run: brew install gh

      # 从 GitHub Release 下载 .ipa 文件
      - name: Download IPA from Release
        run: gh release download ${{ github.event.inputs.release_tag }} --pattern '*.ipa'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # 设置 Ruby 和 Fastlane 环境
      - name: Set up Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # 指定 Ruby 版本
          bundler-cache: true # 缓存 gem 依赖

      # 核心步骤：使用 Fastlane 上传
      - name: Upload to App Store Connect with Fastlane
        run: |
          # 寻找 .ipa 文件路径
          IPA_PATH=$(find . -name "*.ipa" | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "错误：在 Release 中没有找到 .ipa 文件。"
            exit 1
          fi

          # 直接调用 fastlane 的 `upload_to_app_store` action
          # 它会自动处理认证和上传的所有细节
          fastlane run upload_to_app_store \
            api_key_path: "-" \
            api_key: '${{ secrets.APP_STORE_CONNECT_API_KEY }}' \
            api_issuer: '${{ secrets.ISSUER_ID }}' \
            ipa: "$IPA_PATH"
