# 工作流名称
name: Upload IPA to App Store (via Fastfile)

# 触发条件
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: '要上传的 Release 标签'
        required: true
        type: string

# 工作任务
jobs:
  upload:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install gh
          brew install jq

      - name: Download IPA via URL
        run: |
          DOWNLOAD_URL=$(gh release view ${{ github.event.inputs.release_tag }} --json assets | jq -r '.assets[] | select(.name | endswith(".ipa")) | .url')
          if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
            echo "错误：无法获取到 .ipa 文件的下载链接。"
            exit 1
          fi
          curl -L -o app.ipa "$DOWNLOAD_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane
      
      # 已修正：在虚拟机的 HOME 目录下创建 .p8 文件
      - name: Create API Key file
        run: |
          mkdir -p ~/private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > ~/private_keys/AuthKey.p8

      # 最后一步：执行 Fastlane
      - name: Upload to App Store Connect
        env:
          # 传递 ID 信息
          ASC_KEY_ID: ${{ secrets.KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ISSUER_ID }}
        run: fastlane upload
